baseurl = "http://refreshannapolisvalley.com/"
languageCode = "en-ca"
title = "Refresh Annapolis Valley"
theme = "f5"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-37580538-1"

enableRobotsTXT = true

[taxonomies]
subject = "subjects"
person = "people"
organization = "organizations"
topic = "topics"

[params]
  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Google API key for Google Maps
  googleAPIKey = "AIzaSyCvEYk4fnzW_QfClB_mWEZPItiuHzYdw3A"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Events"
  url = "event"
  weight = 1

[[menu.main]]
  name = "Topics"
  url = "topics"
  weight = 2

[[menu.main]]
  name = "People"
  url = "person"
  weight = 3

[[menu.main]]
  name = "Orgs"
  url = "organization"
  weight = 4
